# Generated by Django 4.0.4 on 2022-05-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_compound_c_set'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='compound',
            name='c_set',
        ),
        migrations.AddField(
            model_name='compound',
            name='c_set',
            field=models.ManyToManyField(to='catalog.library'),
        ),
    ]
